### ISSUE TITLE
Show only my plays, show old plays

### ISSUE THREAD

**Issue by artyomtrityak** [board-games-calendar/board-games-calendar#105]

**Comment by artyomtrityak** [comment]
@andrewMuntyan  is it done?

**Comment by andrewMuntyan** [comment]
@artyomtrityak frontend is done. Need some backend. Should i close this issue?

**Comment by artyomtrityak** [comment]
nope, do you want to do it or should i?

**Comment by andrewMuntyan** [comment]
@artyomtrityak i want, but i need discuss some details about realization.
