### ISSUE TITLE
Create script which will add all board games to Mongo (Node)

### ISSUE THREAD

**Issue by artyomtrityak** [board-games-calendar/board-games-calendar#87]

**Comment by wsite** [comment]
Can we use this API http://boardgamegeek.com/thread/99401/boardgamegeek-xml-api http://boardgamegeek.com/guild/1229

**Comment by Vasso** [comment]
Yes, that is good idea! Unfortunately, their games are only available in English.
May be we should parse data from this site http://tesera.ru/games/

**Comment by wsite** [comment]
As you can see the API can seach in russian http://www.boardgamegeek.com/xmlapi/search?search=%D0%BC%D0%BE%D0%BD%D0%BE%D0%BF%D0%BE%D0%BB%D0%B8%D1%8F

**Comment by artyomtrityak** [comment]
@wsite so are you talking about real-time API requests like cities?

**Comment by artyomtrityak** [comment]
@wsite @Vasso so we should merge results from BGG and Tesera

**Comment by wsite** [comment]
@artyomtrityak Possible to use as a search and gradually add its our database? Actually need to understand their API and then discuss what we have.

**Comment by artyomtrityak** [comment]
not needed any more
